![Screenshot 2023-04-13 171030.png]()

Tugas
1. Masukkan iris.csv ke dataframe

In [6]:
import pandas as pd

In [7]:
iris = pd.read_csv('iris.csv')
iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

Penjelasan : Kita importkan terlebih dahulu pandas dengan mengaliaskan pd agar mudah untuk penyebutannya. Lalu kita bisa membaca file iris.csv nya dengan menggunakan perintah pd.read_csv yang ditampung dalam variabel iris. Lalu untuk memanggilnya kita bisa memakai variabel iris. Lalu ketika dirun akan menampilkan dataset iris yang berisi sepal.legth, sepal.width, petal.length, petal.width, dan variety.

2. Normalisasikan setiap attribut iris ke dataframe menggunakan normalisasi min max sehingga
setiap nilai attribut memiliki range 0 – 1. Vbaru = (Vlama - Vmin) / (Vmax - Vmin). Vbaru = nilai
data di suatu sel setelah normalisasi, Vlama = nilai data asli sebelum normalisasi, Vmax = nilai
max dari kolom data tersebut, Vmin = nilai min dari kolom data tersebut

In [8]:
list_iris = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']

for data in list_iris:
  vmin = iris[data].min()
  vmax = iris[data].max()

  iris[data] = (iris[data] - vmin) / (vmax - vmin)

iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0        0.222222     0.625000      0.067797     0.041667     Setosa
1        0.166667     0.416667      0.067797     0.041667     Setosa
2        0.111111     0.500000      0.050847     0.041667     Setosa
3        0.083333     0.458333      0.084746     0.041667     Setosa
4        0.194444     0.666667      0.067797     0.041667     Setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  Virginica
146      0.555556     0.208333      0.677966     0.750000  Virginica
147      0.611111     0.416667      0.711864     0.791667  Virginica
148      0.527778     0.583333      0.745763     0.916667  Virginica
149      0.444444     0.416667      0.694915     0.708333  Virginica

[150 rows x 5 columns]

Penjelasan : pertama tama kita ambil atribut yang dimasukkan ke variabel list_iris. Lalu untuk normalisasinya, kita pakai perulangan for data in list_iris. lalu untuk mencari vmin dan vmax kita pakai index variabel iris dengan index data untuk mencarinya. Setelah mendapatkan hasil vmin dan vmax, kita terapkan rumus Vbaru = (Vlama - Vmin) / (Vmax - Vmin). Lalu untuk mengecek apakah sudah dinormalisasi atau belum, kita bisa memanggil variabel iris untuk menampilkannya.

3. Cari centroid dari data yang telah dinormalisasi. Centroid dihitung dari rata2 seluruh data suatu 
kolom

In [9]:
cluster_iris = iris['variety'].unique()

centroid = dict()

list_iris = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']

for cluster in cluster_iris:
  new_iris = iris[iris['variety'] == cluster]
  centroid[cluster]={}
  for data in list_iris:
    centroid[cluster][data] = new_iris[data].mean()
    
centroid

{'Setosa': {'sepal.length': 0.19611111111111115,
  'sepal.width': 0.595,
  'petal.length': 0.0783050847457627,
  'petal.width': 0.06083333333333333},
 'Versicolor': {'sepal.length': 0.45444444444444443,
  'sepal.width': 0.3208333333333333,
  'petal.length': 0.5525423728813559,
  'petal.width': 0.5108333333333334},
 'Virginica': {'sepal.length': 0.6355555555555555,
  'sepal.width': 0.40583333333333327,
  'petal.length': 0.7715254237288136,
  'petal.width': 0.8025}}

Penjelasan : awal kita memakai iris dengan index variety dan ditampung dalam variabel cluster_iris. Selanjutnya kita buat variabel centroid yang berisi dictionary kosong lalu nanti hasil centroid itu akan ditampung dalam variabel centroid tersebut. Lalu kita ambil setiap atribut yang ada di iris dan dimasukkan dalam variabel list_iris. Lalu kita masuk ke perulangan for cluster in cluster_iris, lalu jika iris variety nya sama dengan cluster, maka akan dimasukkan ke variabel new_iris. Kemudian kita deklarasikan centeroid dengan dictionary kosong. Lalu kita tambahkan lagi perulangan dalam perulangan sebelumnya yaitu for data in list_iris lalu kita cari rata rata dari variabel new_iris dengan index data lalu dimasukkan ke variabel centroid[cluster][data]. Lalu untuk menunjukkan hasilnya kita bisa memanggil variabel centroid tadi.

4. Masukkan iristesting.csv ke dataframe. Normalisasikan iristesting.csv menggunakan vmin dan 
vmax pada data 1

In [10]:
iristesting = pd.read_csv('iristesting.csv')

list_iris = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']

for data in list_iris:
  vmin = iristesting[data].min()
  vmax = iristesting[data].max()

  iristesting[data] = (iristesting[data] - vmin) / (vmax - vmin)

iristesting

    sepal.length  sepal.width  petal.length  petal.width     variety
0           0.24     0.800000      0.000000     0.043478      Setosa
1           0.04     0.000000      0.000000     0.043478      Setosa
2           0.00     0.600000      0.000000     0.000000      Setosa
3           0.24     0.800000      0.065217     0.173913      Setosa
4           0.28     1.000000      0.130435     0.086957      Setosa
5           0.16     0.466667      0.021739     0.043478      Setosa
6           0.28     1.000000      0.065217     0.000000      Setosa
7           0.08     0.600000      0.021739     0.000000      Setosa
8           0.36     0.933333      0.043478     0.000000      Setosa
9           0.24     0.666667      0.021739     0.000000      Setosa
10          0.44     0.200000      0.673913     0.434783  Versicolor
11          0.68     0.466667      0.717391     0.521739  Versicolor
12          0.56     0.200000      0.586957     0.434783  Versicolor
13          0.24     0.000000      0.434783     0.347826  Versicolor
14          0.48     0.266667      0.630435     0.478261  Versicolor
15          0.52     0.466667      0.630435     0.434783  Versicolor
16          0.52     0.400000      0.630435     0.478261  Versicolor
17          0.72     0.400000      0.652174     0.478261  Versicolor
18          0.28     0.133333      0.369565     0.391304  Versicolor
19          0.52     0.333333      0.608696     0.478261  Versicolor
20          0.92     0.533333      0.934783     0.956522   Virginica
21          1.00     0.533333      0.826087     0.913043   Virginica
22          0.56     0.266667      0.826087     0.739130   Virginica
23          0.96     0.600000      1.000000     0.913043   Virginica
24          0.92     0.666667      0.956522     1.000000   Virginica
25          0.92     0.466667      0.847826     0.913043   Virginica
26          0.76     0.133333      0.804348     0.739130   Virginica
27          0.84     0.466667      0.847826     0.782609   Virginica
28          0.72     0.733333      0.891304     0.913043   Virginica
29          0.60     0.466667      0.826087     0.695652   Virginica

Penjelasan : Pertama, seperti tadi untuk membaca file iristesting kita bisa menggunakan perintah pd.read_csv dan dimasukkan ke variabel iristesting. Lalu kita ambil atribut dari iristesting kemudian kita masukkan ke variabel list_iris. Lalu sama seperti tadi, kita normalisasikan terlebih dahulu kemudia kita cari vmin dan vmaxnya menggunakan perulangan for data in list_iris. Lalu untuk mencari v barunya kita bisa menggunakan rumus seperti diatas tadi dan untuk menampilkan hasilnya kita bisa panggil variabel iristesting.

5. Prediksilah kelas data di iristesting.csv menggunakan kriteria kedekatan distance antara setiap 
data di iristesting.csv ke centroid masing2 class di iris. Gunakan euclidean distance

In [11]:
classesiris = iris['variety'].unique()
list_iris = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']

for classes in classesiris:
  distance = 0
  for data in list_iris:
    distance += (iristesting[data] - centroid[classes][data])**2
  distance = distance**(1/2)
  iristesting[classes] = distance

iristesting

,sepal.length,sepal.width,petal.length,petal.width,variety,Setosa,Versicolor,Virginica
0,0.24,0.800000,0.000000,0.043478,Setosa,0.224464,0.894042,1.217866
1,0.04,0.000000,0.000000,0.043478,Setosa,0.620346,0.893545,1.300289
2,0.00,0.600000,0.000000,0.000000,Setosa,0.219811,0.922338,1.296491
3,0.24,0.800000,0.065217,0.173913,Setosa,0.238557,0.791573,1.098100
4,0.28,1.000000,0.130435,0.086957,Setosa,0.417687,0.921707,1.184252
5,0.16,0.466667,0.021739,0.043478,Setosa,0.145857,0.779832,1.169678
6,0.28,1.000000,0.065217,0.000000,Setosa,0.418252,0.995055,1.273708
7,0.08,0.600000,0.021739,0.000000,Setosa,0.142854,0.872265,1.246005
8,0.36,0.933333,0.043478,0.000000,Setosa,0.382417,0.950880,1.236222
9,0.24,0.666667,0.021739,0.000000,Setosa,0.118164,0.841600,1.196112
10,0.44,0.200000,0.673913,0.434783,Versicolor,0.842671,0.187947,0.474714
11,0.68,0.466667,0.717391,0.521739,Versicolor,0.933533,0.315336,0.295691
12,0.56,0.200000,0.586957,0.434783,Versicolor,0.828857,0.180861,0.466216
13,0.24,0.000000,0.434783,0.347826,Versicolor,0.751926,0.435154,0.800805
14,0.48,0.266667,0.630435,0.478261,Versicolor,0.817000,0.103515,0.410612
15,0.52,0.466667,0.630435,0.434783,Versicolor,0.752369,0.193432,0.414941
16,0.52,0.400000,0.630435,0.478261,Versicolor,0.788684,0.133015,0.372055
17,0.72,0.400000,0.652174,0.478261,Versicolor,0.903358,0.296268,0.355726
18,0.28,0.133333,0.369565,0.391304,Versicolor,0.643597,0.336682,0.728924
19,0.52,0.333333,0.608696,0.478261,Versicolor,0.793053,0.093102,0.387626
20,0.92,0.533333,0.934783,0.956522,Virginica,1.436534,0.778874,0.384110
21,1.00,0.533333,0.826087,0.913043,Virginica,1.391215,0.761175,0.405306
22,0.56,0.266667,0.826087,0.739130,Virginica,1.122267,0.375529,0.179077
23,0.96,0.600000,1.000000,0.913043,Virginica,1.469468,0.833973,0.455396
24,0.92,0.666667,0.956522,1.000000,Virginica,1.477312,0.859550,0.471352
25,0.92,0.466667,0.847826,0.913043,Virginica,1.363418,0.697836,0.320392
26,0.76,0.133333,0.804348,0.739130,Virginica,1.232206,0.494010,0.307954
27,0.84,0.466667,0.847826,0.782609,Virginica,1.242652,0.575304,0.227411
28,0.72,0.733333,0.891304,0.913043,Virginica,1.296467,0.719172,0.375438
29,0.60,0.466667,0.826087,0.695652,Virginica,1.068536,0.389151,0.139134

Penjelasan : pertama kita memakai variabel iris dengan index variety lalu juga memakai .unique dan ditampung dalam variabel classesiris. Lalu sama kita ambil setiap atributnya kemudian di buat list dan ditampung dalam variabel list_iris. Lalu kita menggunakan perulangan for classes in classesiris lalu kita deklarasikan variabel distance yang bernilai nol. Lalu kita gunakan perulangan for didalam for kemudian kita buat variabel distance, nah arti variabel tersebut adalah distance itu sendiri dan kita tambahkan dengan operasi (iristesting[data] - centroid[classes][data])**2. Lalu hasil yang dapat akan diakar pangkat kemudian dimasukkan ke variabel distance. Lalu nilai dari distance itu sama dengan nilai iristesting index classes. Lalu untuk memanggil prediksinya kita panggil variabel iristesting.

6. Hitunglah berapa persen klasifikasi yang benar (akurasi) saat memprediksi class

In [12]:
irisresult = iristesting[classesiris]
result = irisresult = irisresult.idxmin(axis=1)

correct = (iristesting['variety'] == result).sum()

total = len(iristesting)
akurasi = (correct / total) * 100
print("akurasi: ", akurasi, "%")

akurasi:  96.66666666666667 %

Penjelelasan : Kita bisa memakai variabel iristesting dnegan index classesiris kemudian ditampung di variabel irisresult. irisresult.idxmin(axis=1) digunakan untuk mengembalikan nilai index minimum dengan sumbu 1 laluditampung dalam variabel result. Lalu variabel correct menampung variabel iristesting dengan index variety = result kemudian akan di sum dan ditampung dalam variabel correct tersebut. Lalu len digunakan untuk menghitung panjang seluruh variabel iristesting dan ditampung dalam variabel total. Lalu untuk menghitung akurasi kita bisa menghitung dengan cara membagi correct dengan total kemudian dikali 100 dan kita mendapatkan hasil akurasi = 96.66666666666667 % .